Fix ID token support
dermesser/yup-oauth2 pull request #184
Opened 2022-09-30 21:07 UTC by blogle

#166 enabled support for ID tokens, but it requires a json response with fields that are not always provided. For example requesting an id token for service-to-service authentication on gcp simply returns a json response with ONLY the `id_token` field. 

This PR rebases #158 onto master, which makes many of the `TokenInfo` fields optional to prevent errors when de-serializing id tokens.

2022-10-02 11:17 UTC, dermesser requested changes

2022-10-02 11:17 UTC, dermesser commented on src/storage.rs
> +            id_token: None,
that's the culprit :)

2022-10-02 11:17 UTC, dermesser commented on examples/custom_client.rs
> +            format!("Bearer {}", token.access_token().ok_or("no access token")?),
did I miss something, or should this be `token.token()`? According to your changes in the `types` module.

2022-10-10 19:48 UTC, blogle commented
:sweat_smile: I should've been more careful in rebasing these changes!

Thanks for taking a look, I updated the PR and ensured that tests are now passing for me locally

2022-10-14 19:47 UTC, dermesser commented
Don't worry about it, happens to me frequently enough too :)

2022-10-16 10:43 UTC, dermesser approved these changes

2022-10-16 10:46 UTC, merged