Add with_sub method for ServiceAccountKey
dermesser/yup-oauth2 pull request #58
Opened 2017-02-22 02:56 UTC by e-oz

required to read email from user accounts (not service account).

2017-02-25 08:56 UTC, Byron commented
@dermesser Somehow the travis notification didn't get through, even though it is happy. What do you think about this PR?

2017-02-25 20:39 UTC, dermesser requested changes
I tested it with the service account example, it at least doesn't break it :) LGTM aside from the one comment.

2017-02-25 20:39 UTC, dermesser commented on src/service_account.rs
> +    pub fn with_sub(key: ServiceAccountKey, client: C, sub: Option<String>) -> ServiceAccountAccess<C> {
how about making the `sub` argument a non-Option `String`? After all, if no sub is needed, `new()` should be used anyway.

2017-02-26 00:20 UTC, e-oz commented on src/service_account.rs
> +    pub fn with_sub(key: ServiceAccountKey, client: C, sub: Option<String>) -> ServiceAccountAccess<C> {
you are right, agree

2017-02-26 08:10 UTC, merged